# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: hierarchical_state_machine
description: >-
  A performant state machine framework inspired by UML.
  Hierarchical parent/child states enable shared event
  handling for cleaner, more efficient logic.
version: 2.2.2
homepage: https://github.com/jtmcdole/hierarchical-state-machine.dart

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  convert: ^3.1.2
  crypto: ^3.0.7
  meta: ^1.17.0

dev_dependencies:
  analyzer: ^10.0.2
  coverage: ^1.15.0
  lcov_format: ^0.0.4
  lints: ^6.1.0
  melos: ^7.0.0-dev.7
  path: ^1.9.1
  test: ^1.25.2
